name: build
on:
  push:
    branches:
      - master
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: |
          cd dist
          git init
          git branch -m dist
          git config --global user.name 'Github Actions'
          git add .
          git commit -m 'Built by Github Action'
          git push "https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}" dist:dist --force